_meta:
  version: '1.0'
  entity_type: shortcut
  uuid: 6b64cc0d-a9c4-426b-8c9f-c24c963e2438
  bundle: default
  default_langcode: en
default:
  title:
    -
      value: 'Add content'
  weight:
    -
      value: -20
  link:
    -
      uri: 'internal:/node/add'
      title: ''
      options: {  }
