<?php

/**
 * @file
 * Primary module hooks for Forcontu Events module.
 */

use Drupal\forcontu_events\Event\UserLoginEvent;
use Drupal\user\UserInterface;

/**
 * Implements hook_user_login.
 */
function forcontu_events_user_login(UserInterface $account) {
  $event = new UserLoginEvent($account);
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::USER_LOGIN);
}
